---
- hosts: all
  become: true
  tasks:

  - name: Install apache2 and php support package
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]



