---
- hosts: all
  become: true
  tasks:

  - name: update repository index(Ubuntu)
    apt:
      update_cache: true
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: Install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"]


  - name: Add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: update repository index(CentOS)
    dnf:
      update_cach: true
    when: ansible_distribution in ["CentOS"]

  - name: Install apache package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"

