---
- hosts: all
  become: true
  tasks:

  - name: Uninstall apache2 package
    apt:
      name: apache2
      state: absent


  - name: Remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent

